-- fill = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- background = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- tab = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- tab_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- tab_separator = {
--   fg = '<colour-value-here>',
--   bg = '<colour-value-here>',
-- },
-- tab_separator_selected = {
--   fg = '<colour-value-here>',
--   bg = '<colour-value-here>',
--   sp = '<colour-value-here>',
--   underline = '<colour-value-here>',
-- },
-- tab_close = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- close_button = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- close_button_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- close_button_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- buffer_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- buffer_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     bold = true,
--     italic = true,
-- },
-- numbers = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- numbers_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- numbers_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     bold = true,
--     italic = true,
-- },
-- diagnostic = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- diagnostic_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- diagnostic_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     bold = true,
--     italic = true,
-- },
-- hint = {
--     fg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- hint_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- hint_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bold = true,
--     italic = true,
-- },
-- hint_diagnostic = {
--     fg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- hint_diagnostic_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- hint_diagnostic_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bold = true,
--     italic = true,
-- },
-- info = {
--     fg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- info_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- info_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bold = true,
--     italic = true,
-- },
-- info_diagnostic = {
--     fg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- info_diagnostic_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- info_diagnostic_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bold = true,
--     italic = true,
-- },
-- warning = {
--     fg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- warning_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- warning_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bold = true,
--     italic = true,
-- },
-- warning_diagnostic = {
--     fg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- warning_diagnostic_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- warning_diagnostic_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bold = true,
--     italic = true,
-- },
-- error = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     sp = '<colour-value-here>',
-- },
-- error_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- error_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bold = true,
--     italic = true,
-- },
-- error_diagnostic = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     sp = '<colour-value-here>',
-- },
-- error_diagnostic_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- error_diagnostic_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     sp = '<colour-value-here>',
--     bold = true,
--     italic = true,
-- },
-- modified = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- modified_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- modified_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
-- },
-- duplicate_selected = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--     italic = true,
-- },
-- duplicate_visible = {
--     fg = '<colour-value-here>',
--     bg = '<colour-value-here>',
--         italic = true,
--     },
--     duplicate = {
--         fg = '<colour-value-here>',
--         bg = '<colour-value-here>',
--         italic = true,
--     },
--     separator_selected = {
--         fg = '<colour-value-here>',
--         bg = '<colour-value-here>',
--     },
--     separator_visible = {
--         fg = '<colour-value-here>',
--         bg = '<colour-value-here>',
--     },
--     separator = {
--         fg = '<colour-value-here>',
--         bg = '<colour-value-here>',
--     },
--     indicator_visible = {
--         fg = '<colour-value-here>',
--         bg = '<colour-value-here>',
--     },
--     indicator_selected = {
--         fg = '<colour-value-here>',
--         bg = '<colour-value-here>',
--     },
--     pick_selected = {
--         fg = '<colour-value-here>',
--         bg = '<colour-value-here>',
--         bold = true,
--         italic = true,
--     },
--     pick_visible = {
--         fg = '<colour-value-here>',
--         bg = '<colour-value-here>',
--         bold = true,
--         italic = true,
--     },
--     pick = {
--         fg = '<colour-value-here>',
--         bg = '<colour-value-here>',
--         bold = true,
--         italic = true,
--     },
--     offset_separator = {
--         fg = '<colour-value-here>',
--         bg = '<colour-value-here>',
--     },
--     trunc_marker = {
--         fg = '<colour-value-here>',
--         bg = '<colour-value-here>',
--     }

return {
    {
        'akinsho/bufferline.nvim',
        version = "*",
        dependencies = 'nvim-tree/nvim-web-devicons',
        opts = {
        },
        config = function()
            -- local _, bufferline = pcall(require, "bufferline")
            local bufferline = require("bufferline")
            bufferline.setup({
                highlights = {
                    background = { fg = "None", bg = "None" },
                    buffer = { fg = "None", bg = "None" },
                    buffer_selected = { bg = "None", bold = true, italic = false },
                    -- buffer = { bg = "None", bold = true, italic = false },
                    group_label = { bg = "None" },
                    separator = { bg = "None" },
                    fill = { bg = "None" },
                    separator_visible = { bg = "None" },
                    separator_selected = { bg = "None" },
                    offset_separator = { bg = "None", italic = false, bold = true },
                },
                options = {
                    --     indicator_icon = ' ',
                    --     separator_style = { '', '' },
                    --     tab_size = 0,
                    --     buffer_close_icon = '',
                    --     modified_icon = '',
                    --     close_icon = '',
                    --
                },
            })
            -- vim.opt.termguicolors = true
        end,
    }
}
