return {}
--- @type LazyPluginSpec
-- return {
--     "christoomey/vim-tmux-navigator",
--     cmd = {
--         "TmuxNavigateLeft",
--         "TmuxNavigateDown",
--         "TmuxNavigateUp",
--         "TmuxNavigateRight",
--         "TmuxNavigatePrevious",
--     },
--     keys = {
--         { "<C-h>", "<cmd><C-U>TmuxNavigateLeft<cr>" },
--         { "<C-j>", "<cmd><C-U>TmuxNavigateDown<cr>" },
--         { "<C-k>", "<cmd><C-U>TmuxNavigateUp<cr>" },
--         { "<C-l>", "<cmd><C-U>TmuxNavigateRight<cr>" },
--         { "<C-Left>", "<cmd>TmuxNavigateLeft<cr>" },
--         { "<C-Down>", "<cmd>TmuxNavigateDown<cr>" },
--         { "<C-Up>", "<cmd>TmuxNavigateUp<cr>" },
--         { "<C-Right>", "<cmd>TmuxNavigateRight<cr>" },
--         { "<C-\\>", "<cmd><C-U>TmuxNavigatePrevious<cr>" },
--     },
-- }
