--- @type LazyPluginSpec
return {
    "xiyaowong/transparent.nvim",
    config = function()
        local transparent = require("transparent")

        vim.keymap.set("n", "<leader>tt", "<cmd>TransparentToggle<CR>", { silent = true, desc = "Toggle transparency" })

        transparent.setup({
            groups = {
                "Normal",
                "NormalNC",
                "NormalFloat",
                "FloatBorder",
                "WinSeparator",
                "Comment",
                "Constant",
                "Special",
                "Identifier",
                "Statement",
                "PreProc",
                "Type",
                "Underlined",
                "Todo",
                "String",
                "Function",
                "Conditional",
                "Repeat",
                "Operator",
                "Structure",
                "LineNr",
                "NonText",
                "SignColumn",
                "CursorLineNr",
                "EndOfBuffer",
            },
            extra_groups = {
                "NormalSB",
                "Folded",
                "NonText",
                "SpecialKey",
                "VertSplit",
                "EndOfBuffer",
                "SignColumn",
                "NeotreeNormal",
                "NeotreeNormalNC",
                "TelescopeNormal",
                "TelescopeBorder",
                "TelescopePromptNormal",
                "TelescopePromptBorder",
                "TelescopePromptTitle",
                "MasonNormal",
                "LazyNormal",
                "LazyButton",
                "WhichKeyNormal",
                "WhichKeyTitle",
                "WhichKeyBorder",
                "SnacksNotifierBorderError",
                "SnacksNotifierBorderDebug",
                "SnacksNotifierBorderWarn",
                "SnacksNotifierBorderInfo",
                "SnacksNotifierTrace",
                "SnacksNotifierError",
                "SnacksNotifierDebug",
                "SnacksNotifierWarn",
                "SnacksNotifierInfo",
                "StatusLine",
                "StatusLineNC",
                "Tabline",
                "TabLineFill",
                "TabLineSel",
                "Winbar",
                "WinbarNC",
            },
            exclude_groups = {},
        })
    end,
}
