-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "tokyonight-moon"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { link = "PreProc" })
hi(0, "@attribute", { link = "PreProc" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.printf", { link = "SpecialChar" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.documentation", { link = "@comment" })
hi(0, "@comment.error", { fg = "#c53b53" })
hi(0, "@comment.hint", { fg = "#4fd6be" })
hi(0, "@comment.info", { fg = "#0db9d7" })
hi(0, "@comment.note", { fg = "#4fd6be" })
hi(0, "@comment.todo", { fg = "#82aaff" })
hi(0, "@comment.warning", { fg = "#ffc777" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Define" })
hi(0, "@constructor", { fg = "#c099ff" })
hi(0, "@constructor.tsx", { fg = "#65bcff" })
hi(0, "@debug", { link = "Debug" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "DiffDelete" })
hi(0, "@diff.plus", { link = "DiffAdd" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { link = "Identifier" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "@function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "@function.method" })
hi(0, "@ibl.indent.char.1", { fg = "#3b4261", nocombine = true })
hi(0, "@ibl.scope.char.1", { fg = "#65bcff", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#65bcff", underline = true })
hi(0, "@ibl.whitespace.char.1", { fg = "#545c7e" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword", { fg = "#fca7ea", italic = true })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.conditional.ternary", { link = "Keyword" })
hi(0, "@keyword.coroutine", { link = "@keyword" })
hi(0, "@keyword.debug", { link = "Debug" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.function", { fg = "#c099ff" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { link = "@operator" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { link = "@keyword" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label", { fg = "#82aaff" })
hi(0, "@lsp.mod.deprecated", { fg = "#ebb3d8" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.class", { link = "@structure" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.deriveHelper", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.formatSpecifier", { link = "@markup.list" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.generic", { link = "@variable" })
hi(0, "@lsp.type.interface", { fg = "#83c3fc" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.lifetime", { link = "@keyword.storage" })
hi(0, "@lsp.type.macro", { link = "@macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.namespace.python", { link = "@variable" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.selfTypeKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@structure" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { sp = "#c53b53", undercurl = true })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.keyword.injected", { link = "@keyword" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.type.defaultLibrary", { fg = "#589ed7" })
hi(0, "@lsp.typemod.typeAlias.defaultLibrary", { fg = "#589ed7" })
hi(0, "@lsp.typemod.variable.callable", { link = "@function" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "@constant" })
hi(0, "@macro", { link = "Macro" })
hi(0, "@markup", { link = "@none" })
hi(0, "@markup.emphasis", { italic = true })
hi(0, "@markup.environment", { link = "Macro" })
hi(0, "@markup.environment.name", { link = "Type" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.heading.1", { fg = "#f7b3ad" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#000000", fg = "#000000", nocombine = true, sp = "#cdc4c6", underdouble = true })
hi(0, "@markup.heading.1.markdown", { bold = true, fg = "#82aaff" })
hi(0, "@markup.heading.2", { fg = "#e9be8e" })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#000000", fg = "#000000", nocombine = true, sp = "#cdc4c6", underline = true })
hi(0, "@markup.heading.2.markdown", { bold = true, fg = "#ffc777" })
hi(0, "@markup.heading.3", { fg = "#c5cd91" })
hi(0, "@markup.heading.3.markdown", { bold = true, fg = "#c3e88d" })
hi(0, "@markup.heading.4", { fg = "#99d7b5" })
hi(0, "@markup.heading.4.markdown", { bold = true, fg = "#4fd6be" })
hi(0, "@markup.heading.5", { fg = "#85d6df" })
hi(0, "@markup.heading.5.markdown", { bold = true, fg = "#c099ff" })
hi(0, "@markup.heading.6", { fg = "#9fcbf9" })
hi(0, "@markup.heading.6.markdown", { bold = true, fg = "#fca7ea" })
hi(0, "@markup.heading.7.markdown", { bold = true, fg = "#ff966c" })
hi(0, "@markup.heading.8.markdown", { bold = true, fg = "#ff757f" })
hi(0, "@markup.link", { fg = "#4fd6be" })
hi(0, "@markup.link.label", { link = "SpecialChar" })
hi(0, "@markup.link.label.symbol", { link = "Identifier" })
hi(0, "@markup.link.url", { link = "Underlined" })
hi(0, "@markup.list", { fg = "#89ddff" })
hi(0, "@markup.list.checked", { fg = "#4fd6be" })
hi(0, "@markup.list.markdown", { bold = true, fg = "#ff966c" })
hi(0, "@markup.list.unchecked", { fg = "#82aaff" })
hi(0, "@markup.math", { link = "Special" })
hi(0, "@markup.quote", { link = "@string.special" })
hi(0, "@markup.raw", { link = "String" })
hi(0, "@markup.raw.block", { link = "@markup.raw" })
hi(0, "@markup.raw.markdown_inline", { bg = "#444a73", fg = "#82aaff" })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@module", { link = "Include" })
hi(0, "@module.builtin", { fg = "#ff757f" })
hi(0, "@namespace", { link = "Identifier" })
hi(0, "@namespace.builtin", { link = "@variable.builtin" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@operator", { fg = "#89ddff" })
hi(0, "@parameter", { fg = "#9fcbf9" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { fg = "#4fd6be" })
hi(0, "@punctuation.bracket", { fg = "#828bb8" })
hi(0, "@punctuation.delimiter", { fg = "#89ddff" })
hi(0, "@punctuation.special", { fg = "#89ddff" })
hi(0, "@punctuation.special.markdown", { fg = "#ff966c" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.documentation", { fg = "#ffc777" })
hi(0, "@string.escape", { fg = "#c099ff" })
hi(0, "@string.regexp", { fg = "#b4f9f8" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.path", { link = "Directory" })
hi(0, "@string.special.symbol", { link = "@constant" })
hi(0, "@string.special.url", { link = "@markup.link.url" })
hi(0, "@string.special.vimdoc", { link = "@constant" })
hi(0, "@structure", { link = "Structure" })
hi(0, "@symbol", { link = "Keyword" })
hi(0, "@tag", { link = "Label" })
hi(0, "@tag.attribute", { link = "@property" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { link = "Delimiter" })
hi(0, "@tag.delimiter.tsx", { fg = "#6582c3" })
hi(0, "@tag.javascript", { fg = "#ff757f" })
hi(0, "@tag.tsx", { fg = "#ff757f" })
hi(0, "@text.danger", { link = "ErrorMsg" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { link = "Special" })
hi(0, "@text.note", { link = "MoreMsg" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { link = "WarningMsg" })
hi(0, "@type.builtin", { fg = "#589ed7" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@type.qualifier", { link = "@keyword" })
hi(0, "@variable", { fg = "#c8d3f5" })
hi(0, "@variable.builtin", { fg = "#ff757f" })
hi(0, "@variable.member", { fg = "#4fd6be" })
hi(0, "@variable.parameter", { fg = "#ffc777" })
hi(0, "@variable.parameter.builtin", { fg = "#f4c990" })
hi(0, "Added", { fg = "#c5cd91" })
hi(0, "Beacon", { bg = "#f3e9ec" })
hi(0, "Bold", { bold = true, fg = "#c8d3f5" })
hi(0, "BqfPreviewFloat", { link = "NormalFloat" })
hi(0, "BqfPreviewTitle", { link = "FloatTitle" })
hi(0, "BqfSign", { fg = "#99d7b5" })
hi(0, "BufferCurrent", { bg = "#000000", bold = true, fg = "#c7c7c7" })
hi(0, "BufferCurrentIcon", { bg = "#000000" })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#1e1e1e", bold = true, fg = "#c7c7c7" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#3e3e3e", bold = true, fg = "#c7c7c7" })
hi(0, "BufferInactive", { bg = "#000000", fg = "#cdc4c6" })
hi(0, "BufferInactiveIcon", { bg = "#000000" })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#1e1e1e", fg = "#cdc4c6" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#3e3e3e", fg = "#cdc4c6" })
hi(0, "BufferLineBuffer", { fg = "#857d7f" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#cdc4c6" })
hi(0, "BufferLineBufferVisible", { fg = "#cdc4c6" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#c5cd91", fg = "#000000" })
hi(0, "BufferLineTabSelected", { bg = "#c5cd91", bold = true, fg = "#000000" })
hi(0, "BufferManagerIndicator", { fg = "#9b9ea4" })
hi(0, "BufferManagerModified", { bold = true })
hi(0, "BufferManagerShortcut", { bold = true, underline = true })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#c5cd91", bold = true, fg = "#000000" })
hi(0, "BufferVisible", { bg = "#000000", bold = true, fg = "#cdc4c6" })
hi(0, "BufferVisibleIcon", { bg = "#000000" })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#1e1e1e", bold = true, fg = "#cdc4c6" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#3e3e3e", bold = true, fg = "#cdc4c6" })
hi(0, "Changed", { fg = "#99d7b5" })
hi(0, "Character", { fg = "#c3e88d" })
hi(0, "CmpItemAbbr", { fg = "#cdc4c6" })
hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
hi(0, "CmpItemAbbrMatch", { bold = true })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
hi(0, "CmpItemKind", { fg = "#cdc4c6" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstructor", { link = "Type" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumMember", { link = "Structure" })
hi(0, "CmpItemKindEvent", { link = "Exception" })
hi(0, "CmpItemKindField", { link = "Structure" })
hi(0, "CmpItemKindFile", { link = "Tag" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindModule", { link = "Structure" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindProperty", { link = "Structure" })
hi(0, "CmpItemKindReference", { link = "Tag" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindText", { link = "Normal" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindUnit", { link = "Special" })
hi(0, "CmpItemKindValue", { link = "Identifier" })
hi(0, "CmpItemKindVariable", { link = "Delimiter" })
hi(0, "CmpItemMenu", { fg = "#cdc4c6" })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocFadeOut", { link = "Comment" })
hi(0, "CocMarkdownLink", { fg = "#9fcbf9" })
hi(0, "CocMenuSel", { bg = "#3e3e3e" })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { fg = "#9fcbf9" })
hi(0, "CocSelectedText", { fg = "#e9be8e" })
hi(0, "ColorColumn", { bg = "#1b1d2b" })
hi(0, "Comment", { fg = "#636da6", italic = true })
hi(0, "ComplHint", { fg = "#444a73" })
hi(0, "Conceal", { fg = "#737aa2" })
hi(0, "Constant", { fg = "#ff966c" })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { bg = "#c8d3f5", fg = "#222436" })
hi(0, "CursorColumn", { bg = "#2f334d" })
hi(0, "CursorIM", { bg = "#c8d3f5", fg = "#222436" })
hi(0, "CursorLine", { bg = "#2f334d" })
hi(0, "CursorLineFold", { fg = "#3e3e3e" })
hi(0, "CursorLineNr", { bold = true, fg = "#ff966c" })
hi(0, "CursorLineSign", { fg = "#3e3e3e" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#c5cd91" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#f7b3ad" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Comment" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "WarningMsg" })
hi(0, "Debug", { fg = "#ff966c" })
hi(0, "Definitions", { fg = "#c5cd91" })
hi(0, "DefinitionsIcon", { fg = "#85d6df" })
hi(0, "Delimiter", { link = "Special" })
hi(0, "DiagnosticDeprecated", { sp = "#ebb3d8", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#c53b53" })
hi(0, "DiagnosticFloatingError", { bg = "#000000", fg = "#ebb3d8" })
hi(0, "DiagnosticFloatingHint", { bg = "#000000", fg = "#99d7b5" })
hi(0, "DiagnosticFloatingInfo", { bg = "#000000", fg = "#9fcbf9" })
hi(0, "DiagnosticFloatingOk", { bg = "#000000", fg = "#c5cd91" })
hi(0, "DiagnosticFloatingWarn", { bg = "#000000", fg = "#e9be8e" })
hi(0, "DiagnosticHint", { fg = "#4fd6be" })
hi(0, "DiagnosticInfo", { fg = "#0db9d7" })
hi(0, "DiagnosticOk", { fg = "#c5cd91" })
hi(0, "DiagnosticUnderlineError", { sp = "#c53b53", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#4fd6be", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#0db9d7", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#c5cd91", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ffc777", undercurl = true })
hi(0, "DiagnosticUnnecessary", { fg = "#444a73" })
hi(0, "DiagnosticVirtualTextError", { bg = "#322639", fg = "#c53b53" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#273644", fg = "#4fd6be" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#203346", fg = "#0db9d7" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#38343d", fg = "#ffc777" })
hi(0, "DiagnosticWarn", { fg = "#ffc777" })
hi(0, "DiffAdd", { bg = "#2a4556" })
hi(0, "DiffChange", { bg = "#252a3f" })
hi(0, "DiffDelete", { bg = "#4b2a3d" })
hi(0, "DiffText", { bg = "#394b70" })
hi(0, "Directory", { fg = "#82aaff" })
hi(0, "EndOfBuffer", { blend = 0, fg = "#222436" })
hi(0, "Error", { fg = "#c53b53" })
hi(0, "ErrorMsg", { fg = "#c53b53" })
hi(0, "FinderParam", { fg = "#e9be8e" })
hi(0, "FinderSpinner", { fg = "#c5cd91" })
hi(0, "FinderSpinnerBorder", { fg = "#c7c7c7" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { fg = "#f7b3ad" })
hi(0, "Float", { link = "Constant" })
hi(0, "FloatBorder", { fg = "#589ed7" })
hi(0, "FloatTitle", { fg = "#589ed7" })
hi(0, "FoldColumn", { fg = "#636da6" })
hi(0, "Folded", { bg = "#3b4261", fg = "#82aaff" })
hi(0, "Foo", { bg = "#ff007c", fg = "#c8d3f5" })
hi(0, "Function", { fg = "#82aaff" })
hi(0, "FzfLuaBorder", { fg = "#589ed7" })
hi(0, "FzfLuaBufFlagAlt", { link = "Special" })
hi(0, "FzfLuaBufFlagCur", { link = "CursorLineNr" })
hi(0, "FzfLuaBufNr", { link = "DiagnosticHint" })
hi(0, "FzfLuaCursor", { link = "IncSearch" })
hi(0, "FzfLuaDirPart", { fg = "#828bb8" })
hi(0, "FzfLuaFilePart", { link = "FzfLuaFzfNormal" })
hi(0, "FzfLuaFzfCursorLine", { link = "Visual" })
hi(0, "FzfLuaFzfNormal", { fg = "#c8d3f5" })
hi(0, "FzfLuaFzfPointer", { fg = "#ff007c" })
hi(0, "FzfLuaFzfSeparator", { fg = "#ff966c" })
hi(0, "FzfLuaHeaderBind", { link = "@punctuation.special" })
hi(0, "FzfLuaHeaderText", { link = "Title" })
hi(0, "FzfLuaLiveSym", { link = "DiagnosticHint" })
hi(0, "FzfLuaNormal", { fg = "#c8d3f5" })
hi(0, "FzfLuaPath", { link = "Directory" })
hi(0, "FzfLuaPathColNr", { link = "DiagnosticHint" })
hi(0, "FzfLuaPathLineNr", { link = "DiagnosticInfo" })
hi(0, "FzfLuaPreviewTitle", { fg = "#589ed7" })
hi(0, "FzfLuaTabMarker", { link = "DiagnosticHint" })
hi(0, "FzfLuaTabTitle", { link = "Title" })
hi(0, "FzfLuaTitle", { fg = "#ff966c" })
hi(0, "GitSignsAdd", { fg = "#c5cd91" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsChange", { fg = "#e9be8e" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsDelete", { fg = "#ebb3d8" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsUntracked", { fg = "#85d6df" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "HelpviewCode", { bg = "#000000" })
hi(0, "HelpviewCodeLanguage", { bg = "#000000" })
hi(0, "HelpviewHeading1", { link = "@markup.heading.1" })
hi(0, "HelpviewHeading2", { link = "@markup.heading.2" })
hi(0, "HelpviewHeading3", { link = "@markup.heading.3" })
hi(0, "HelpviewHeading4", { link = "@markup.heading.4" })
hi(0, "HelpviewInlineCode", { bg = "#000000" })
hi(0, "HelpviewMentionlink", { fg = "#c7c7c7", underline = true })
hi(0, "HelpviewOptionlink", { fg = "#e9be8e", underline = true })
hi(0, "HelpviewTaglink", { bold = true, fg = "#c7c7c7" })
hi(0, "HelpviewTitle", { link = "Title" })
hi(0, "HopNextKey", { bold = true, fg = "#c5cd91", nocombine = true })
hi(0, "HopNextKey1", { bold = true, fg = "#f7b3ad", nocombine = true })
hi(0, "HopNextKey2", { bold = true, fg = "#a9a0a2", nocombine = true })
hi(0, "HopPreview", { bold = true, fg = "#e9be8e", nocombine = true })
hi(0, "HopUnmatched", { fg = "#3e3e3e" })
hi(0, "HydraAmaranth", { fg = "#c9bdf6" })
hi(0, "HydraBlue", { fg = "#85d6df" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { fg = "#f7b3ad" })
hi(0, "HydraRed", { fg = "#ebb3d8" })
hi(0, "HydraTeal", { fg = "#99d7b5" })
hi(0, "IblIndent", { fg = "#3b4261", nocombine = true })
hi(0, "IblScope", { fg = "#65bcff", nocombine = true })
hi(0, "IblWhitespace", { link = "NonText" })
hi(0, "Identifier", { fg = "#c099ff" })
hi(0, "Ignore", {})
hi(0, "IncSearch", { bg = "#ff966c", fg = "#1b1d2b" })
hi(0, "IndentBlanklineChar", { fg = "#3b4261", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#65bcff", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#c7c7c7", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#9fcbf9", nocombine = true })
hi(0, "IndentBlanklineIndent2", { fg = "#99d7b5", nocombine = true })
hi(0, "IndentBlanklineIndent3", { fg = "#e9be8e", nocombine = true })
hi(0, "IndentBlanklineIndent4", { fg = "#ebb3d8", nocombine = true })
hi(0, "IndentBlanklineIndent5", { fg = "#85d6df", nocombine = true })
hi(0, "IndentBlanklineIndent6", { fg = "#c5cd91", nocombine = true })
hi(0, "IndentBlanklineIndent7", { fg = "#f7b3ad", nocombine = true })
hi(0, "IndentBlanklineIndent8", { fg = "#c9bdf6", nocombine = true })
hi(0, "Italic", { fg = "#c8d3f5", italic = true })
hi(0, "Keyword", { fg = "#86e1fc", italic = true })
hi(0, "LSOutlinePreviewBorder", { fg = "#c7c7c7" })
hi(0, "LazyButton", { bg = "#1e1e1e" })
hi(0, "LazyButtonActive", { bg = "#3e3e3e" })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyH1", { bg = "#3e3e3e", bold = true, fg = "#c7c7c7" })
hi(0, "LazyProgressDone", { bold = true, fg = "#ff007c" })
hi(0, "LazyProgressTodo", { bold = true, fg = "#3b4261" })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabel", { bold = true, fg = "#e9be8e", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, fg = "#99d7b5", nocombine = true })
hi(0, "LeapMatch", { bold = true, fg = "#c5cd91", nocombine = true, underline = true })
hi(0, "LineNr", { fg = "#3b4261" })
hi(0, "LineNrAbove", { fg = "#3b4261" })
hi(0, "LineNrBelow", { fg = "#3b4261" })
hi(0, "LspCodeLens", { fg = "#636da6" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspInfoBorder", { fg = "#589ed7" })
hi(0, "LspInlayHint", { bg = "#24283c", fg = "#545c7e" })
hi(0, "LspKindArray", { link = "@punctuation.bracket" })
hi(0, "LspKindBoolean", { link = "@boolean" })
hi(0, "LspKindClass", { link = "@type" })
hi(0, "LspKindColor", { link = "Special" })
hi(0, "LspKindConstant", { link = "@constant" })
hi(0, "LspKindConstructor", { link = "@constructor" })
hi(0, "LspKindEnum", { link = "@lsp.type.enum" })
hi(0, "LspKindEnumMember", { link = "@lsp.type.enumMember" })
hi(0, "LspKindEvent", { link = "Special" })
hi(0, "LspKindField", { link = "@variable.member" })
hi(0, "LspKindFile", { link = "Normal" })
hi(0, "LspKindFolder", { link = "Directory" })
hi(0, "LspKindFunction", { link = "@function" })
hi(0, "LspKindInterface", { link = "@lsp.type.interface" })
hi(0, "LspKindKey", { link = "@variable.member" })
hi(0, "LspKindKeyword", { link = "@lsp.type.keyword" })
hi(0, "LspKindMethod", { link = "@function.method" })
hi(0, "LspKindModule", { link = "@module" })
hi(0, "LspKindNamespace", { link = "@module" })
hi(0, "LspKindNull", { link = "@constant.builtin" })
hi(0, "LspKindNumber", { link = "@number" })
hi(0, "LspKindObject", { link = "@constant" })
hi(0, "LspKindOperator", { link = "@operator" })
hi(0, "LspKindPackage", { link = "@module" })
hi(0, "LspKindProperty", { link = "@property" })
hi(0, "LspKindReference", { link = "@markup.link" })
hi(0, "LspKindSnippet", { link = "Conceal" })
hi(0, "LspKindString", { link = "@string" })
hi(0, "LspKindStruct", { link = "@lsp.type.struct" })
hi(0, "LspKindText", { link = "@markup" })
hi(0, "LspKindTypeParameter", { link = "@lsp.type.typeParameter" })
hi(0, "LspKindUnit", { link = "@lsp.type.struct" })
hi(0, "LspKindValue", { link = "@string" })
hi(0, "LspKindVariable", { link = "@variable" })
hi(0, "LspReferenceRead", { bg = "#3b4261" })
hi(0, "LspReferenceText", { bg = "#3b4261" })
hi(0, "LspReferenceWrite", { bg = "#3b4261" })
hi(0, "LspSagaAutoPreview", { fg = "#9fcbf9" })
hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
hi(0, "LspSagaCodeActionBorder", { fg = "#c7c7c7" })
hi(0, "LspSagaCodeActionContent", { fg = "#cdc4c6" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#85d6df" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#c7c7c7" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#c7c7c7" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { fg = "#f7b3ad" })
hi(0, "LspSagaFinderSelection", { fg = "#99d7b5" })
hi(0, "LspSagaHoverBorder", { fg = "#c7c7c7" })
hi(0, "LspSagaLspFinderBorder", { fg = "#c7c7c7" })
hi(0, "LspSagaRenameBorder", { fg = "#c7c7c7" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#c7c7c7" })
hi(0, "LspSignatureActiveParameter", { bg = "#262f50", bold = true })
hi(0, "MarkviewPalette0", { bg = "#000000", fg = "#c7c7c7" })
hi(0, "MarkviewPalette0Bg", { bg = "#000000" })
hi(0, "MarkviewPalette0Fg", { fg = "#c7c7c7" })
hi(0, "MarkviewPalette0Sign", { fg = "#c7c7c7" })
hi(0, "MarkviewPalette1", { bg = "#190012", fg = "#ebb3d8" })
hi(0, "MarkviewPalette1Bg", { bg = "#190012" })
hi(0, "MarkviewPalette1Fg", { fg = "#ebb3d8" })
hi(0, "MarkviewPalette1Sign", { fg = "#ebb3d8" })
hi(0, "MarkviewPalette2", { bg = "#1f0001", fg = "#f7b3ad" })
hi(0, "MarkviewPalette2Bg", { bg = "#1f0001" })
hi(0, "MarkviewPalette2Fg", { fg = "#f7b3ad" })
hi(0, "MarkviewPalette2Sign", { fg = "#f7b3ad" })
hi(0, "MarkviewPalette3", { bg = "#321c00", fg = "#e9be8e" })
hi(0, "MarkviewPalette3Bg", { bg = "#321c00" })
hi(0, "MarkviewPalette3Fg", { fg = "#e9be8e" })
hi(0, "MarkviewPalette3Sign", { fg = "#e9be8e" })
hi(0, "MarkviewPalette4", { bg = "#232600", fg = "#c5cd91" })
hi(0, "MarkviewPalette4Bg", { bg = "#232600" })
hi(0, "MarkviewPalette4Fg", { fg = "#c5cd91" })
hi(0, "MarkviewPalette4Sign", { fg = "#c5cd91" })
hi(0, "MarkviewPalette5", { bg = "#002a17", fg = "#99d7b5" })
hi(0, "MarkviewPalette5Bg", { bg = "#002a17" })
hi(0, "MarkviewPalette5Fg", { fg = "#99d7b5" })
hi(0, "MarkviewPalette5Sign", { fg = "#99d7b5" })
hi(0, "MarkviewPalette6", { bg = "#00363b", fg = "#85d6df" })
hi(0, "MarkviewPalette6Bg", { bg = "#00363b" })
hi(0, "MarkviewPalette6Fg", { fg = "#85d6df" })
hi(0, "MarkviewPalette6Sign", { fg = "#85d6df" })
hi(0, "MarkviewPalette7", { bg = "#00162e", fg = "#9fcbf9" })
hi(0, "MarkviewPalette7Bg", { bg = "#00162e" })
hi(0, "MarkviewPalette7Fg", { fg = "#9fcbf9" })
hi(0, "MarkviewPalette7Sign", { fg = "#9fcbf9" })
hi(0, "MasonError", { fg = "#ebb3d8" })
hi(0, "MasonHeader", { bg = "#85d6df", bold = true, fg = "#000000" })
hi(0, "MasonHeaderSecondary", { bg = "#9fcbf9", bold = true, fg = "#000000" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { fg = "#c7c7c7" })
hi(0, "MasonHighlightBlock", { bg = "#c7c7c7", fg = "#000000" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#85d6df", fg = "#000000" })
hi(0, "MasonHighlightSecondary", { fg = "#85d6df" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#3e3e3e", fg = "#000000" })
hi(0, "MasonMutedBlockBold", { bg = "#3e3e3e", bold = true, fg = "#000000" })
hi(0, "MatchParen", { bold = true, fg = "#ff966c" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { bg = "#3b4261" })
hi(0, "MiniCursorwordCurrent", { bg = "#3b4261" })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { bg = "#e26a75", fg = "#1b1d2b" })
hi(0, "MiniDepsTitleSame", { link = "Comment" })
hi(0, "MiniDepsTitleUpdate", { bg = "#b8db87", fg = "#1b1d2b" })
hi(0, "MiniDiffSignAdd", { fg = "#b8db87" })
hi(0, "MiniDiffSignChange", { fg = "#7ca1f2" })
hi(0, "MiniDiffSignDelete", { fg = "#e26a75" })
hi(0, "MiniFilesFile", { fg = "#c8d3f5" })
hi(0, "MiniFilesTitleFocused", { bold = true, fg = "#589ed7" })
hi(0, "MiniHipatternsFixme", { bg = "#c53b53", bold = true, fg = "#1b1d2b" })
hi(0, "MiniHipatternsHack", { bg = "#ffc777", bold = true, fg = "#1b1d2b" })
hi(0, "MiniHipatternsNote", { bg = "#4fd6be", bold = true, fg = "#1b1d2b" })
hi(0, "MiniHipatternsTodo", { bg = "#0db9d7", bold = true, fg = "#1b1d2b" })
hi(0, "MiniIconsAzure", { fg = "#0db9d7" })
hi(0, "MiniIconsBlue", { fg = "#82aaff" })
hi(0, "MiniIconsCyan", { fg = "#4fd6be" })
hi(0, "MiniIconsGreen", { fg = "#c3e88d" })
hi(0, "MiniIconsGrey", { fg = "#c8d3f5" })
hi(0, "MiniIconsOrange", { fg = "#ff966c" })
hi(0, "MiniIconsPurple", { fg = "#fca7ea" })
hi(0, "MiniIconsRed", { fg = "#ff757f" })
hi(0, "MiniIconsYellow", { fg = "#ffc777" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#65bcff", nocombine = true })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#ebb3d8" })
hi(0, "MiniJump", { bg = "#ff007c", fg = "#ffffff" })
hi(0, "MiniJump2dDim", { link = "Comment" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#ff007c", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#1e2030", fg = "#4fd6be", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { bold = true, fg = "#ff966c", nocombine = true })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { link = "Title" })
hi(0, "MiniMapSymbolView", { link = "Delimiter" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { fg = "#4fd6be" })
hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { fg = "#0db9d7" })
hi(0, "MiniPickPromptCaret", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniPickPromptPrefix", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniSnippetsCurrent", { sp = "#e9be8e", underdouble = true })
hi(0, "MiniSnippetsCurrentReplace", { sp = "#ebb3d8", underdouble = true })
hi(0, "MiniSnippetsFinal", { sp = "#c5cd91", underdouble = true })
hi(0, "MiniSnippetsUnvisited", { sp = "#99d7b5", underdouble = true })
hi(0, "MiniSnippetsVisited", { sp = "#9fcbf9", underdouble = true })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#ffc777", italic = true })
hi(0, "MiniStarterHeader", { fg = "#82aaff" })
hi(0, "MiniStarterInactive", { fg = "#636da6", italic = true })
hi(0, "MiniStarterItem", { fg = "#c8d3f5" })
hi(0, "MiniStarterItemBullet", { fg = "#589ed7" })
hi(0, "MiniStarterItemPrefix", { fg = "#ffc777" })
hi(0, "MiniStarterQuery", { fg = "#0db9d7" })
hi(0, "MiniStarterSection", { fg = "#65bcff" })
hi(0, "MiniStatuslineDevinfo", { bg = "#3b4261", fg = "#828bb8" })
hi(0, "MiniStatuslineFileinfo", { bg = "#3b4261", fg = "#828bb8" })
hi(0, "MiniStatuslineFilename", { bg = "#2f334d", fg = "#828bb8" })
hi(0, "MiniStatuslineInactive", { bg = "#1e2030", fg = "#82aaff" })
hi(0, "MiniStatuslineModeCommand", { bg = "#ffc777", bold = true, fg = "#1b1d2b" })
hi(0, "MiniStatuslineModeInsert", { bg = "#c3e88d", bold = true, fg = "#1b1d2b" })
hi(0, "MiniStatuslineModeNormal", { bg = "#82aaff", bold = true, fg = "#1b1d2b" })
hi(0, "MiniStatuslineModeOther", { bg = "#4fd6be", bold = true, fg = "#1b1d2b" })
hi(0, "MiniStatuslineModeReplace", { bg = "#ff757f", bold = true, fg = "#1b1d2b" })
hi(0, "MiniStatuslineModeVisual", { bg = "#c099ff", bold = true, fg = "#1b1d2b" })
hi(0, "MiniSurround", { bg = "#ff966c", fg = "#1b1d2b" })
hi(0, "MiniTablineCurrent", { bg = "#3b4261", fg = "#c8d3f5" })
hi(0, "MiniTablineFill", { bg = "#1b1d2b" })
hi(0, "MiniTablineHidden", { bg = "#1e2030", fg = "#737aa2" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#3b4261", fg = "#ffc777" })
hi(0, "MiniTablineModifiedHidden", { bg = "#1e2030", fg = "#bd9664" })
hi(0, "MiniTablineModifiedVisible", { bg = "#1e2030", fg = "#ffc777" })
hi(0, "MiniTablineTabpagesection", { bg = "#3b4261" })
hi(0, "MiniTablineTrunc", { bg = "#000000", bold = true, fg = "#c7c7c7" })
hi(0, "MiniTablineVisible", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#ff757f" })
hi(0, "MiniTestPass", { bold = true, fg = "#c3e88d" })
hi(0, "MiniTrailspace", { bg = "#ff757f" })
hi(0, "ModeMsg", { bold = true, fg = "#828bb8" })
hi(0, "MoreMsg", { fg = "#82aaff" })
hi(0, "MsgArea", { blend = 0, fg = "#828bb8" })
hi(0, "MsgSeparator", { blend = 0, fg = "#857d7f" })
hi(0, "NeoTreeDimText", { fg = "#3e3e3e" })
hi(0, "NeoTreeDotfile", { fg = "#a9a0a2" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { fg = "#3e3e3e" })
hi(0, "NeoTreeGitAdded", { fg = "#c5cd91" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#f7b3ad" })
hi(0, "NeoTreeGitDeleted", { fg = "#ebb3d8" })
hi(0, "NeoTreeGitModified", { fg = "#e9be8e" })
hi(0, "NeoTreeGitUnstaged", { fg = "#c9bdf6" })
hi(0, "NeoTreeGitUntracked", { fg = "#99d7b5" })
hi(0, "NeoTreeMessage", { bg = "#1e1e1e", fg = "#cdc4c6" })
hi(0, "NeoTreeModified", { fg = "#dfd6d8" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#c7c7c7" })
hi(0, "NeoTreeTabInactive", { fg = "#857d7f" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#3e3e3e", fg = "#857d7f" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#1e1e1e", fg = "#1e1e1e" })
hi(0, "NeogitBranch", { fg = "#c099ff" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { bg = "#2a4556", fg = "#b8db87" })
hi(0, "NeogitDiffContextHighlight", { bg = "#2f334c", fg = "#828bb8" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#4b2a3d", fg = "#e26a75" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { bg = "#2f334d", fg = "#c8d3f5" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#3b4261", fg = "#82aaff" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NeogitRemote", { fg = "#fca7ea" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#85d6df" })
hi(0, "NoiceConfirmBorder", { fg = "#e9be8e" })
hi(0, "NonText", { fg = "#545c7e" })
hi(0, "Normal", { blend = 0, fg = "#c8d3f5" })
hi(0, "NormalFloat", { fg = "#c8d3f5" })
hi(0, "NormalNC", { blend = 0, fg = "#c8d3f5" })
hi(0, "NormalSB", { fg = "#828bb8" })
hi(0, "NotifyDEBUGBorder", { fg = "#c5cd91" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBorder", { fg = "#ebb3d8" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyINFOBorder", { fg = "#9fcbf9" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#99d7b5" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#e9be8e" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#c5cd91" })
hi(0, "NvimTreeFolderIcon", { fg = "#857d7f" })
hi(0, "NvimTreeGitDeleted", { fg = "#ebb3d8" })
hi(0, "NvimTreeGitDirty", { fg = "#e9be8e" })
hi(0, "NvimTreeGitMerge", { fg = "#f7b3ad" })
hi(0, "NvimTreeGitNew", { fg = "#99d7b5" })
hi(0, "NvimTreeGitRenamed", { fg = "#c9bdf6" })
hi(0, "NvimTreeGitStaged", { fg = "#c5cd91" })
hi(0, "NvimTreeImageFile", { fg = "#f7b3ad" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#c7c7c7" })
hi(0, "NvimTreeSpecialFile", { fg = "#c7c7c7", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#9fcbf9" })
hi(0, "NvimTreeWindowPicker", { bg = "#3e3e3e", bold = true, fg = "#cdc4c6" })
hi(0, "Operator", { fg = "#89ddff" })
hi(0, "OutlineDetail", { fg = "#3e3e3e" })
hi(0, "OutlineFoldPrefix", { fg = "#e9be8e" })
hi(0, "OutlineIndentEvn", { fg = "#857d7f" })
hi(0, "OutlineIndentOdd", { fg = "#cdc4c6" })
hi(0, "Pmenu", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "PmenuMatch", { bg = "#1e2030", fg = "#65bcff" })
hi(0, "PmenuMatchSel", { bg = "#363c58", fg = "#65bcff" })
hi(0, "PmenuSbar", { bg = "#27293a" })
hi(0, "PmenuSel", { bg = "#363c58" })
hi(0, "PmenuThumb", { bg = "#3b4261" })
hi(0, "PounceAccept", { bg = "#e9be8e", bold = true, fg = "#000000", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#c5cd91", bold = true, fg = "#000000", nocombine = true })
hi(0, "PounceGap", { bg = "#3e3e3e", bold = true, fg = "#000000", nocombine = true })
hi(0, "PounceMatch", { bg = "#cdc4c6", bold = true, fg = "#000000", nocombine = true })
hi(0, "PreProc", { fg = "#86e1fc" })
hi(0, "Question", { fg = "#82aaff" })
hi(0, "QuickFixLine", { bg = "#2d3f76", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#85d6df" })
hi(0, "RainbowDelimiterCyan", { fg = "#99d7b5" })
hi(0, "RainbowDelimiterGreen", { fg = "#c5cd91" })
hi(0, "RainbowDelimiterOrange", { fg = "#f7b3ad" })
hi(0, "RainbowDelimiterRed", { fg = "#ebb3d8" })
hi(0, "RainbowDelimiterViolet", { fg = "#c9bdf6" })
hi(0, "RainbowDelimiterYellow", { fg = "#e9be8e" })
hi(0, "References", { fg = "#c5cd91" })
hi(0, "ReferencesIcon", { fg = "#85d6df" })
hi(0, "Removed", { fg = "#ebb3d8" })
hi(0, "RenderMarkdownBullet", { fg = "#c7c7c7" })
hi(0, "RenderMarkdownChecked", { link = "DiagnosticOk" })
hi(0, "RenderMarkdownCode", { bg = "#000000" })
hi(0, "RenderMarkdownCodeInline", { bg = "#000000" })
hi(0, "RenderMarkdownDash", { fg = "#c7c7c7" })
hi(0, "RenderMarkdownH1", { fg = "#f7b3ad" })
hi(0, "RenderMarkdownH1Bg", { bg = "#1f0001" })
hi(0, "RenderMarkdownH2", { fg = "#e9be8e" })
hi(0, "RenderMarkdownH2Bg", { bg = "#321c00" })
hi(0, "RenderMarkdownH3", { fg = "#c5cd91" })
hi(0, "RenderMarkdownH3Bg", { bg = "#232600" })
hi(0, "RenderMarkdownH4", { fg = "#99d7b5" })
hi(0, "RenderMarkdownH4Bg", { bg = "#002a17" })
hi(0, "RenderMarkdownH5", { fg = "#85d6df" })
hi(0, "RenderMarkdownH5Bg", { bg = "#00363b" })
hi(0, "RenderMarkdownH6", { fg = "#9fcbf9" })
hi(0, "RenderMarkdownH6Bg", { bg = "#00162e" })
hi(0, "RenderMarkdownTodo", { link = "Todo" })
hi(0, "RenderMarkdownUnchecked", { link = "DiagnosticWarn" })
hi(0, "Search", { bg = "#3e68d7", fg = "#c8d3f5" })
hi(0, "SignColumn", { fg = "#3b4261" })
hi(0, "SignColumnSB", { fg = "#3b4261" })
hi(0, "SnacksDashboardDesc", { fg = "#86e1fc" })
hi(0, "SnacksDashboardDir", { fg = "#545c7e" })
hi(0, "SnacksDashboardFooter", { fg = "#65bcff" })
hi(0, "SnacksDashboardHeader", { fg = "#82aaff" })
hi(0, "SnacksDashboardIcon", { fg = "#65bcff" })
hi(0, "SnacksDashboardKey", { fg = "#ff966c" })
hi(0, "SnacksDashboardSpecial", { fg = "#fca7ea" })
hi(0, "SnacksIndent", { fg = "#3b4261", nocombine = true })
hi(0, "SnacksIndent1", { fg = "#82aaff", nocombine = true })
hi(0, "SnacksIndent2", { fg = "#ffc777", nocombine = true })
hi(0, "SnacksIndent3", { fg = "#c3e88d", nocombine = true })
hi(0, "SnacksIndent4", { fg = "#4fd6be", nocombine = true })
hi(0, "SnacksIndent5", { fg = "#c099ff", nocombine = true })
hi(0, "SnacksIndent6", { fg = "#fca7ea", nocombine = true })
hi(0, "SnacksIndent7", { fg = "#ff966c", nocombine = true })
hi(0, "SnacksIndent8", { fg = "#ff757f", nocombine = true })
hi(0, "SnacksIndentScope", { fg = "#65bcff", nocombine = true })
hi(0, "SnacksInputBorder", { fg = "#ffc777" })
hi(0, "SnacksInputIcon", { fg = "#65bcff" })
hi(0, "SnacksInputTitle", { fg = "#ffc777" })
hi(0, "SnacksNotifierBorderDebug", { fg = "#3c4163" })
hi(0, "SnacksNotifierBorderError", { fg = "#632d42" })
hi(0, "SnacksNotifierBorderInfo", { fg = "#1a6076" })
hi(0, "SnacksNotifierBorderTrace", { fg = "#79587e" })
hi(0, "SnacksNotifierBorderWarn", { fg = "#7a6550" })
hi(0, "SnacksNotifierDebug", { fg = "#c8d3f5" })
hi(0, "SnacksNotifierError", { fg = "#c8d3f5" })
hi(0, "SnacksNotifierIconDebug", { fg = "#636da6" })
hi(0, "SnacksNotifierIconError", { fg = "#c53b53" })
hi(0, "SnacksNotifierIconInfo", { fg = "#0db9d7" })
hi(0, "SnacksNotifierIconTrace", { fg = "#fca7ea" })
hi(0, "SnacksNotifierIconWarn", { fg = "#ffc777" })
hi(0, "SnacksNotifierInfo", { fg = "#c8d3f5" })
hi(0, "SnacksNotifierTitleDebug", { fg = "#636da6" })
hi(0, "SnacksNotifierTitleError", { fg = "#c53b53" })
hi(0, "SnacksNotifierTitleInfo", { fg = "#0db9d7" })
hi(0, "SnacksNotifierTitleTrace", { fg = "#fca7ea" })
hi(0, "SnacksNotifierTitleWarn", { fg = "#ffc777" })
hi(0, "SnacksNotifierTrace", { fg = "#c8d3f5" })
hi(0, "SnacksNotifierWarn", { fg = "#c8d3f5" })
hi(0, "SnacksPickerBoxTitle", { fg = "#ff966c" })
hi(0, "SnacksPickerInputBorder", { fg = "#ff966c" })
hi(0, "SnacksPickerInputTitle", { fg = "#ff966c" })
hi(0, "SnacksPickerPickWin", { bg = "#3e68d7", bold = true, fg = "#c8d3f5" })
hi(0, "SnacksPickerPickWinCurrent", { bg = "#ff007c", bold = true, fg = "#c8d3f5" })
hi(0, "SnacksPickerSelected", { fg = "#ff007c" })
hi(0, "SnacksPickerToggle", { link = "SnacksProfilerBadgeInfo" })
hi(0, "SnacksProfilerBadgeInfo", { bg = "#29334a", fg = "#65bcff" })
hi(0, "SnacksProfilerBadgeTrace", { bg = "#24283c", fg = "#545c7e" })
hi(0, "SnacksProfilerIconInfo", { bg = "#365272", fg = "#65bcff" })
hi(0, "SnacksProfilerIconTrace", { bg = "#293047", fg = "#545c7e" })
hi(0, "SnacksScratchDesc", { link = "SnacksProfilerBadgeInfo" })
hi(0, "SnacksScratchKey", { link = "SnacksProfilerIconInfo" })
hi(0, "SnacksZenIcon", { fg = "#fca7ea" })
hi(0, "Sneak", { bg = "#f7b3ad", fg = "#000000" })
hi(0, "SneakLabel", { bg = "#f7b3ad", bold = true, fg = "#000000" })
hi(0, "SneakScope", { bg = "#f3e9ec", fg = "#000000" })
hi(0, "SnippetTabstop", { bg = "#321c00" })
hi(0, "Special", { fg = "#65bcff" })
hi(0, "SpecialKey", { fg = "#545c7e" })
hi(0, "SpellBad", { sp = "#c53b53", undercurl = true })
hi(0, "SpellCap", { sp = "#ffc777", undercurl = true })
hi(0, "SpellLocal", { sp = "#0db9d7", undercurl = true })
hi(0, "SpellRare", { sp = "#4fd6be", undercurl = true })
hi(0, "Statement", { fg = "#c099ff" })
hi(0, "StatusLine", { bg = "#1e2030", fg = "#828bb8" })
hi(0, "StatusLineNC", { bg = "#1e2030", fg = "#3b4261" })
hi(0, "String", { fg = "#c3e88d" })
hi(0, "Substitute", { bg = "#ff757f", fg = "#1b1d2b" })
hi(0, "TabLine", { bg = "#1e2030", fg = "#3b4261" })
hi(0, "TabLineFill", { bg = "#1b1d2b" })
hi(0, "TabLineSel", { bg = "#82aaff", fg = "#1b1d2b" })
hi(0, "TargetFileName", { fg = "#cdc4c6" })
hi(0, "TelescopeBorder", { fg = "#589ed7" })
hi(0, "TelescopeMatching", { bold = true })
hi(0, "TelescopeMultiSelection", { bg = "#3e3e3e" })
hi(0, "TelescopeNormal", { fg = "#c8d3f5" })
hi(0, "TelescopePromptBorder", { fg = "#ff966c" })
hi(0, "TelescopePromptTitle", { fg = "#ff966c" })
hi(0, "TelescopeResultsComment", { fg = "#545c7e" })
hi(0, "TelescopeSelection", { bg = "#1e1e1e" })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { bold = true, fg = "#82aaff" })
hi(0, "Todo", { bg = "#ffc777", fg = "#222436" })
hi(0, "TroubleCount", { bold = true, fg = "#c7c7c7" })
hi(0, "TroubleFoldIcon", { bold = true, fg = "#c7c7c7" })
hi(0, "TroubleIndent", { fg = "#3e3e3e" })
hi(0, "TroubleLocation", { fg = "#a9a0a2" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleText", { fg = "#cdc4c6" })
hi(0, "TroubleTextError", { link = "TroubleText" })
hi(0, "TroubleTextHint", { link = "TroubleText" })
hi(0, "TroubleTextInformation", { link = "TroubleText" })
hi(0, "TroubleTextWarning", { link = "TroubleText" })
hi(0, "Type", { fg = "#65bcff" })
hi(0, "VertSplit", { blend = 0, fg = "#1b1d2b" })
hi(0, "Visual", { bg = "#2d3f76" })
hi(0, "VisualNOS", { bg = "#2d3f76" })
hi(0, "WarningMsg", { fg = "#ffc777" })
hi(0, "WhichKey", { fg = "#86e1fc" })
hi(0, "WhichKeyBorder", { link = "FloatBorder" })
hi(0, "WhichKeyDesc", { fg = "#c099ff" })
hi(0, "WhichKeyFloat", { bg = "#000000", fg = "#cdc4c6" })
hi(0, "WhichKeyGroup", { fg = "#82aaff" })
hi(0, "WhichKeyIconAzure", { link = "MiniIconsAzure" })
hi(0, "WhichKeyIconBlue", { link = "MiniIconsBlue" })
hi(0, "WhichKeyIconCyan", { link = "MiniIconsCyan" })
hi(0, "WhichKeyIconGreen", { link = "MiniIconsGreen" })
hi(0, "WhichKeyIconGrey", { link = "MiniIconsGrey" })
hi(0, "WhichKeyIconOrange", { link = "MiniIconsOrange" })
hi(0, "WhichKeyIconPurple", { link = "MiniIconsPurple" })
hi(0, "WhichKeyIconRed", { link = "MiniIconsRed" })
hi(0, "WhichKeyIconYellow", { link = "MiniIconsYellow" })
hi(0, "WhichKeyNormal", {})
hi(0, "WhichKeySeparator", { fg = "#636da6" })
hi(0, "WhichKeyValue", { fg = "#737aa2" })
hi(0, "Whitespace", { fg = "#3b4261" })
hi(0, "WildMenu", { bg = "#2d3f76" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { blend = 0, bold = true, fg = "#1b1d2b" })
hi(0, "debugBreakpoint", { bg = "#203346", fg = "#0db9d7" })
hi(0, "diffAdded", { bg = "#2a4556", fg = "#b8db87" })
hi(0, "diffChanged", { bg = "#252a3f", fg = "#7ca1f2" })
hi(0, "diffFile", { fg = "#82aaff" })
hi(0, "diffIndexLine", { fg = "#c099ff" })
hi(0, "diffLine", { fg = "#636da6" })
hi(0, "diffNewFile", { bg = "#2a4556", fg = "#65bcff" })
hi(0, "diffOldFile", { bg = "#4b2a3d", fg = "#65bcff" })
hi(0, "diffRemoved", { bg = "#4b2a3d", fg = "#e26a75" })
hi(0, "dosIniLabel", { link = "@property" })
hi(0, "gitcommitBranch", { bold = true, fg = "#f7b3ad" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#e9be8e" })
hi(0, "gitcommitDiscardedType", { fg = "#85d6df" })
hi(0, "gitcommitHeader", { link = "Title" })
hi(0, "gitcommitOverflow", { fg = "#e9be8e" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#c5cd91" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { fg = "#c5cd91" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { fg = "#99d7b5" })
hi(0, "healthError", { fg = "#c53b53" })
hi(0, "healthSuccess", { fg = "#4fd6be" })
hi(0, "healthWarning", { fg = "#ffc777" })
hi(0, "helpCommand", { bg = "#444a73", fg = "#82aaff" })
hi(0, "helpExample", { fg = "#636da6" })
hi(0, "htmlH1", { bold = true, fg = "#c099ff" })
hi(0, "htmlH2", { bold = true, fg = "#82aaff" })
hi(0, "lCursor", { bg = "#c8d3f5", fg = "#222436" })
hi(0, "markdownH1", { link = "@markup.heading.1" })
hi(0, "markdownH2", { link = "@markup.heading.2" })
hi(0, "markdownH3", { link = "@markup.heading.3" })
hi(0, "markdownH4", { link = "@markup.heading.4" })
hi(0, "markdownH5", { link = "@markup.heading.5" })
hi(0, "markdownH6", { link = "@markup.heading.6" })
hi(0, "qfFileName", { fg = "#82aaff" })
hi(0, "qfLineNr", { fg = "#737aa2" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1b1d2b"
g.terminal_color_1 = "#ff757f"
g.terminal_color_2 = "#c3e88d"
g.terminal_color_3 = "#ffc777"
g.terminal_color_4 = "#82aaff"
g.terminal_color_5 = "#c099ff"
g.terminal_color_6 = "#86e1fc"
g.terminal_color_7 = "#828bb8"
g.terminal_color_8 = "#444a73"
g.terminal_color_9 = "#ff8d94"
g.terminal_color_10 = "#c7fb6d"
g.terminal_color_11 = "#ffd8ab"
g.terminal_color_12 = "#9ab8ff"
g.terminal_color_13 = "#caabff"
g.terminal_color_14 = "#b2ebff"
g.terminal_color_15 = "#c8d3f5"
